version: "2.3"
services:
  server:
    build: .
    ports:
      # expose port 80 to host machine and target container port 8000 (wsgi)
      - "80:8000"
    networks:
      - con5_net
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:5.0.0
    expose:
      - "6379"
    networks:
      - con5_net

networks:
  # good practice to have a dedicated network rather than using default
  con5_net:
